version: '2'
services:
  app:
    container_name: orxatasoftware_worker
    image: orxatasoftware/worker:0.0.1.RELEASE
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8888:80
    volumes:
      - .:/app
    networks:
      - laravel
    environment:
      docker: 'true'
      WEB_DOCUMENT_ROOT: '/app/public'
      WEB_NO_CACHE_PATTERN: '\.(.*)$$'
      working_dir: '/app'
  mysql:
    image: mariadb:latest
    restart: always
    ports:
      - 8889:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_DATABASE: 'worker'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - mysql:db
    ports:
     - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBRITARY=1

networks:
  laravel:
    driver: bridge
