version: '2'
services:
  app:
    container_name: orxatasoftware_worker
    image: orxatasoftware/worker:0.0.2.DEV
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8888:80
    volumes:
      - .:/app
    environment:
      docker: 'true'
      WEB_DOCUMENT_ROOT: '/app/public'
      WEB_NO_CACHE_PATTERN: '\.(.*)$$'
      working_dir: '/app'
  mysql:
    image: mariadb:latest
    ports:
      - 8889:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_DATABASE: 'worker'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
networks:
  laravel:
    driver: bridge
